name: Unit Testing

on:
  push:
    branches:
      - main
      - rebuild
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-and-scan:
    runs-on: ubuntu-latest

    services:
      thor-solo:
        image: zzdockerzz/thor-solo
        ports:
          - 8669:8669

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
